### ISSUE TITLE
Get Nomadwiki running

### ISSUE THREAD

**Issue by tillwenke** [Hitchwiki/.github#8]
*restore Nomadwiki from SQL dump
see
for content https://github.com/Hitchwiki/nomadwiki
for how to https://www.mediawiki.org/wiki/Manual:Restoring_a_wiki_from_backup

**Comment by thumbsup82** [comment]
> [@thumbsup82](https://github.com/thumbsup82) can you specify (or give a link) about what you mean/ did with special/import?

The standard function within a wiki. As described here: [https://www.mediawiki.org/wiki/Manual:Importing_XML_dumps](url)

**Comment by noahsmindfuck** [comment]
> Can be downloaded at [http://nomadwiki.org/nomad-dump.xml.gz](url)

That gives me an error:
```
This view no longer exists
Select another view to use this project.
```

**Comment by guaka** [comment]
Just added the XML dump at https://hitchwiki.org/dumps [here](https://hitchwiki.org/dumps/nomad-dump.xml.gz)

**Comment by guaka** [comment]
> https://github.com/Hitchwiki/nomadwiki

It's a private repo, it also contains the SQL dump which contains user email addresses etc.
@noahsmindfuck, I just gave you access to the repo.

**Comment by guaka** [comment]
https://nomadwiki.org/ back
